name: TODO Scanner

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  scan_todos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get branch name
        id: vars
        run: echo "branch_name=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Debug Branch and TODO Collection
        run: |
          echo "Branch name: ${{ env.branch_name }}"
          # Prepare the header for todo.md
          echo "# TODOs in the Codebase" > todo.md
          echo "" >> todo.md
          
          # Use grep to search for TODO comments, format each line, and append to todo.md
          grep -r -n "TODO" \
          --exclude=*.yml \
          --exclude=todo.md \
          --exclude-dir={.git,node_modules,build,.github} \
          . | while IFS=: read -r filepath line todo; do
          echo "[${{ env.branch_name }}] ${filepath}:${line} ${todo}" >> todo.md
          done
          
          # Display the contents of todo.md for debugging
          cat todo.md

      - name: Commit and push todo.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if todo.md has any changes and commit if it does
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add todo.md
            git commit -m "Update TODO list [skip ci]"
            git push
          fi
