name: TODO Scanner

on:
  push:
    branches:
      - '**'  # Trigger on all branches

jobs:
  scan_todos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Switch to todo-list branch
        run: |
          # Check if the todo-list branch exists, and create it if not
          git fetch origin
          if git show-ref --verify --quiet refs/heads/todo-list; then
            git checkout todo-list
          else
            git checkout -b todo-list
          fi

      - name: Scan codebase for TODOs
        run: |
          echo "# TODOs in the Codebase" > todo.md
          echo "" >> todo.md
          
          # Search for TODO comments and append them to todo.md
          grep -r -n "TODO" \
            --exclude=*.yml \
            --exclude=todo.md \
            --exclude-dir={.git,node_modules,build,.github} \
            . | while IFS=: read -r filepath line todo; do
            echo "- ${filepath}:${line} ${todo}" >> todo.md
          done

      - name: Commit and push todo.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check for changes in todo.md and commit
          if [ -n "$(git status --porcelain)" ]; then
            git add todo.md
            git commit -m "Update TODO list [skip ci]"
            git push origin todo-list  # Push to the todo-list branch
          else
            echo "No changes in todo.md to commit."
          fi
