name: TODO Scanner

on:
  push:
    branches:
      - main  # Run the workflow only on pushes to the main branch
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC (optional)

jobs:
  scan_todos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get branch name
      id: vars
      run: echo "branch_name=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

    - name: Scan codebase for TODOs
      run: |
        # Prepare the header for todo.md
        echo "# TODOs in the Codebase" > todo.md
        echo "" >> todo.md
        
        # Search for TODOs and format them with branch, file path, line number, and comment
        grep -r -n "TODO" --exclude-dir={.git,node_modules,build} . | while IFS=: read -r filepath line todo; do
          echo "[${{ env.branch_name }}] ${filepath}:${line} ${todo}" >> todo.md
        done

    - name: Commit and push todo.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Check if todo.md has any changes and commit if it does
        if [ -n "$(git status --porcelain)" ]; then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add todo.md
          git commit -m "Update TODO list [skip ci]"
          git push
        fi
